letheanVPN/blockchain-iz

src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h
- local issue: https://github.com/valiant1x/intensecoin/issues/43
- upstream issue: https://github.com/monero-project/monero#3230
- upstream pull request: https://github.com/monero-project/monero#3231
=> patch in fix from upstream to address issue #43

src/cryptonote_basic/cryptonote_basic.h
=> fix merged mining block interpretation

src/daemonizer/posix_fork.cpp
Fix for possible conflict with monero wallet running on the same machine.
=> Fix possible conflict with monero

contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/syncobj.h, src/wallet/api/wallet.cpp
PR for https://github.com/valiant1x/intensecoinwallet/issues/41
Still a work in progress. Header paths have been fixed but at least one other issue remains.
=> Add support for Boost 1.67

ci/macos.10.12.sh, ci/package-artifacts/CHANGELOG.txt, ci/package-artifacts/README.txt, ci/package-artifacts/start.bat, ci/package-artifacts/start.sh, ci/run.sh, ci/ubuntu.16.04.x86_64.sh, ci/windows.10.x86.sh, ci/windows.10.x86_64.sh
- added start scripts and readme
- version stamp now uses tag if present
- added win32 CI target
- adjusted package naming
=> improved onboarding and package stamping

src/wallet/wallet2.cpp
monero PR https://github.com/monero-project/monero/pull/4491
=> clear found out for every tx key

src/cryptonote_core/blockchain.cpp
Monero https://github.com/monero-project/monero/pull/3726
=> Fix for unknown block crash

src/cryptonote_basic/miner.cpp
https://github.com/monero-project/monero/pull/4700
Fixes #151
=> Fix build with boost 1.69

external/unbound/configure_checks.cmake
Fixes compiling on static-linux-armv7 and possibly other architectures.
=> Update unbound submodule

src/crypto/slow-hash.c
=> define uint64 for arm7 to fix cross-compilation

src/wallet/wallet2.cpp
https://github.com/monero-project/monero/pull/5216
=> wallet2: fix mishandling rct outputs in coinbase tx

src/cryptonote_basic/hardfork.cpp
Monero PR: https://github.com/monero-project/monero/pull/5225
=> Hardfork: fix fork determination for historical heights

contrib/epee/include/storages/portable_storage_from_bin.h
https://github.com/monero-project/monero/commit/39169ace09f702b8ae66fe373424e5c0b1326a6d
=> epee: basic sanity check on allocation size from untrusted source

ci/package-artifacts/README.txt, src/common/util.cpp, src/common/util.h, src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp, src/daemonizer/windows_daemonizer.inl
Update blockchain data path to 
CRYPTONOTE_NAME=Lethean,  
Unix: ~/CRYPTONOTE_NAME/data
Mac: /Library/Application Support/CRYPTONOTE_NAME/data, 
Window: /ProgramData/CRYPTONOTE_NAME/data
=> Update blockchain data path 

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, CMakeLists.txt, external/unbound/CMakeLists.txt
Also added simple artifact upload
=> Bundled windows exes with dll's

CMakeLists.txt, src/cryptonote_core/blockchain.cpp
=> Testnet window size change

contrib/epee/include/net/abstract_tcp_server2.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/net/levin_protocol_handler_async.h, src/cryptonote_core/blockchain.cpp
This fixes dead p2p connection accumulation, ip bind issues and adds proper( good enough ) v7 HF timestamp.
=> Fix p2p stuff and v7 HF

src/p2p/net_node.h, src/p2p/net_node.inl
This includes :
- Failed connections are closed after failed handshake.
- Seed nodes don't get added to list twice, when going through fallback nodes
- Nodes don't try to connect to already connected seed node. ( was happening when couldn't find min number of peers (8) and no more seed nodes )
=> P2p dead connections fix and more

src/common/dns_utils.cpp, src/cryptonote_basic/checkpoints.cpp, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp
This adds basic necessities for DNS checkpoints.
Though they will not work until DNSSEC is setup.
=> Dns checkpoints

src/common/dns_utils.cpp, src/cryptonote_basic/checkpoints.cpp
* Adds fresh DS anchor for DNSSEC validation.
* Uses public DNS by default
=> DNSSEC tweak

src/cryptonote_basic/cryptonote_basic_impl.cpp
=> Just a small fix
